@startuml

GameWorld *-- BoardSystem
GameWorld *-- TurnSystem
BoardSystem *-- ColumnObject
ColumnObject *-- DiscObject
TurnSystem *-- Controller
Controller <|-- PlayerController
Controller <|-- AIController

@enduml
